#!/usr/bin/env python3
"""Expand skills.json: 8 skills × 3 stages × 5 items = 120."""
import json
from pathlib import Path

ROOT = Path("/workspace/quintile")

def item(id, stage, prompt, answer, solution, accept, difficulty=None):
    d = {"easy": 1, "medium": 2, "hard": 3}[stage]
    return {
        "id": id,
        "stage": stage,
        "difficulty": difficulty if difficulty is not None else d,
        "prompt": prompt,
        "answer": answer,
        "solution": solution,
        "accept": accept,
    }

# Existing items kept; classified into stages; new items fill to 5 per stage.
SKILLS = [
  {
    "id": "indices", "order": 1,
    "title": "Indices & surds",
    "blurb": "Powers, roots, and rationalising a denominator.",
    "hlLink": "You need this before logs, binomial expansions, and exact trig values.",
    "items": [
      # easy (keep 1,4)
      item("indices-1", "easy",
           r"Simplify $\dfrac{2^{3}\times 2^{4}}{2^{5}}$.",
           r"$4$", r"Add the indices in the product, then subtract: $2^{3+4-5}=2^{2}=4$.",
           ["4", "2^2"]),
      item("indices-4", "easy",
           r"Rationalise $\dfrac{1}{\sqrt{2}}$.",
           r"$\dfrac{\sqrt{2}}{2}$", r"Multiply numerator and denominator by $\sqrt{2}$.",
           ["sqrt(2)/2", "1/sqrt(2)"]),
      item("indices-e3", "easy",
           r"Simplify $5^{0}$.",
           r"$1$", r"Any non-zero number to the power $0$ is $1$.",
           ["1"]),
      item("indices-e4", "easy",
           r"Simplify $3^{-2}$.",
           r"$\dfrac{1}{9}$", r"$3^{-2}=\dfrac{1}{3^{2}}=\dfrac{1}{9}$.",
           ["1/9"]),
      item("indices-e5", "easy",
           r"Simplify $\sqrt{36}$.",
           r"$6$", r"$6^{2}=36$.",
           ["6"]),
      # medium (keep 2,3,5)
      item("indices-2", "medium",
           r"Simplify $\dfrac{(x^{5})^{2}}{x^{4}}$.",
           r"$x^{6}$", r"$(x^{5})^{2}=x^{10}$, then $x^{10}/x^{4}=x^{6}$.",
           ["x^6"]),
      item("indices-3", "medium",
           r"Write $\sqrt{48}$ in simplest surd form.",
           r"$4\sqrt{3}$", r"$48=16\times 3$, so $\sqrt{48}=4\sqrt{3}$.",
           ["4sqrt(3)", "4*sqrt(3)"]),
      item("indices-5", "medium",
           r"Evaluate $8^{2/3}$.",
           r"$4$", r"$8^{1/3}=2$ and $2^{2}=4$.",
           ["4"]),
      item("indices-m4", "medium",
           r"Simplify $\dfrac{a^{7}}{a^{2}\cdot a^{3}}$.",
           r"$a^{2}$", r"$a^{2}\cdot a^{3}=a^{5}$, so $a^{7}/a^{5}=a^{2}$.",
           ["a^2"]),
      item("indices-m5", "medium",
           r"Rationalise $\dfrac{6}{\sqrt{3}}$.",
           r"$2\sqrt{3}$", r"$\dfrac{6}{\sqrt{3}}\cdot\dfrac{\sqrt{3}}{\sqrt{3}}=\dfrac{6\sqrt{3}}{3}=2\sqrt{3}$.",
           ["2sqrt(3)", "2*sqrt(3)"]),
      # hard
      item("indices-h1", "hard",
           r"Simplify $\dfrac{(2x^{3})^{4}}{4x^{5}}$.",
           r"$4x^{7}$", r"$(2x^{3})^{4}=16x^{12}$, then $16x^{12}/(4x^{5})=4x^{7}$.",
           ["4x^7"]),
      item("indices-h2", "hard",
           r"Write $\dfrac{\sqrt{50}}{\sqrt{2}}$ in simplest form.",
           r"$5$", r"$\sqrt{50}/\sqrt{2}=\sqrt{25}=5$.",
           ["5"]),
      item("indices-h3", "hard",
           r"Rationalise $\dfrac{1}{2+\sqrt{3}}$.",
           r"$2-\sqrt{3}$", r"Multiply by $2-\sqrt{3}$: numerator $2-\sqrt{3}$, denominator $4-3=1$.",
           ["2-sqrt(3)"]),
      item("indices-h4", "hard",
           r"Simplify $\left(\dfrac{27}{8}\right)^{-2/3}$.",
           r"$\dfrac{4}{9}$", r"$\left(\dfrac{8}{27}\right)^{2/3}=\dfrac{4}{9}$.",
           ["4/9"]),
      item("indices-h5", "hard",
           r"Simplify $\dfrac{x^{-2}y^{3}}{x^{3}y^{-1}}$.",
           r"$\dfrac{y^{4}}{x^{5}}$", r"$x^{-2-3}y^{3-(-1)}=x^{-5}y^{4}=\dfrac{y^{4}}{x^{5}}$.",
           ["y^4/x^5", "(y^4)/(x^5)"]),
    ],
  },
  {
    "id": "manipulation", "order": 2,
    "title": "Expand, factor, rearrange",
    "blurb": "The algebra you are expected to do without thinking.",
    "hlLink": "Every HL paper hides marks inside clean factorising.",
    "items": [
      item("manipulation-1", "easy",
           r"Expand $(x-3)(x+4)$.",
           r"$x^{2}+x-12$", r"$x^{2}+4x-3x-12=x^{2}+x-12$.",
           ["x^2+x-12", "x^2-12+x"]),
      item("manipulation-4", "easy",
           r"Solve $\dfrac{2x+1}{3}=5$.",
           r"$x=7$", r"$2x+1=15$, so $2x=14$ and $x=7$.",
           ["7", "x=7"]),
      item("manipulation-e3", "easy",
           r"Expand $3(x-2)$.",
           r"$3x-6$", r"$3\cdot x-3\cdot 2=3x-6$.",
           ["3x-6"]),
      item("manipulation-e4", "easy",
           r"Factorise $6x+9$.",
           r"$3(2x+3)$", r"Common factor $3$.",
           ["3(2x+3)", "3(3+2x)"]),
      item("manipulation-e5", "easy",
           r"Make $x$ the subject of $y=2x+5$.",
           r"$x=\dfrac{y-5}{2}$", r"$y-5=2x$, so $x=(y-5)/2$.",
           ["(y-5)/2", "x=(y-5)/2"]),
      item("manipulation-2", "medium",
           r"Factorise $x^{2}-5x+6$.",
           r"$(x-2)(x-3)$", r"Look for two numbers multiplying to $6$ and adding to $-5$: $-2$ and $-3$.",
           ["(x-2)(x-3)", "(x-3)(x-2)"]),
      item("manipulation-5", "medium",
           r"Expand $(2x-1)^{2}$.",
           r"$4x^{2}-4x+1$", r"$(2x-1)^{2}=4x^{2}-2\cdot 2x\cdot 1+1$.",
           ["4x^2-4x+1"]),
      item("manipulation-3", "medium",
           r"Simplify $\dfrac{x^{2}-9}{x-3}$, for $x\neq 3$.",
           r"$x+3$", r"$x^{2}-9=(x-3)(x+3)$, so the factor $x-3$ cancels.",
           ["x+3", "3+x"]),
      item("manipulation-m4", "medium",
           r"Expand $(x+2)(x^{2}-x+3)$.",
           r"$x^{3}+x^{2}+x+6$", r"$x^{3}-x^{2}+3x+2x^{2}-2x+6=x^{3}+x^{2}+x+6$.",
           ["x^3+x^2+x+6"]),
      item("manipulation-m5", "medium",
           r"Factorise $x^{2}-16$.",
           r"$(x-4)(x+4)$", r"Difference of squares.",
           ["(x-4)(x+4)", "(x+4)(x-4)"]),
      item("manipulation-h1", "hard",
           r"Factorise $2x^{2}+7x-15$.",
           r"$(2x-3)(x+5)$", r"Numbers for $2\cdot(-15)=-30$ that add to $7$: $10$ and $-3$. Grouping gives $(2x-3)(x+5)$.",
           ["(2x-3)(x+5)", "(x+5)(2x-3)"]),
      item("manipulation-h2", "hard",
           r"Simplify $\dfrac{x^{2}+5x+6}{x^{2}+x-6}$.",
           r"$\dfrac{x+2}{x-2}$", r"$(x+2)(x+3)/((x+3)(x-2))=(x+2)/(x-2)$ for $x\neq -3$.",
           ["(x+2)/(x-2)", "(x+2)/(x-2)"]),
      item("manipulation-h3", "hard",
           r"Expand $(x-1)^{3}$.",
           r"$x^{3}-3x^{2}+3x-1$", r"$(x-1)(x^{2}-2x+1)=x^{3}-3x^{2}+3x-1$.",
           ["x^3-3x^2+3x-1"]),
      item("manipulation-h4", "hard",
           r"Make $r$ the subject of $A=4\pi r^{2}$.",
           r"$r=\sqrt{\dfrac{A}{4\pi}}$", r"$r^{2}=A/(4\pi)$, so $r=\sqrt{A/(4\pi)}$.",
           ["sqrt(A/(4pi))", "sqrt(A/(4*pi))", "r=sqrt(A/(4pi))"]),
      item("manipulation-h5", "hard",
           r"Factorise $x^{3}-8$.",
           r"$(x-2)(x^{2}+2x+4)$", r"Difference of cubes: $a^{3}-b^{3}=(a-b)(a^{2}+ab+b^{2})$ with $a=x$, $b=2$.",
           ["(x-2)(x^2+2x+4)"]),
    ],
  },
  {
    "id": "linear", "order": 3,
    "title": "Lines & equations",
    "blurb": "Linear equations, inequalities, and gradient.",
    "hlLink": "Tangents, normals, and simultaneous conditions all start here.",
    "items": [
      item("linear-1", "easy",
           r"Solve $3x-7=11$.",
           r"$x=6$", r"$3x=18$, so $x=6$.",
           ["6", "x=6"]),
      item("linear-3", "easy",
           r"Solve the inequality $4x+1<13$.",
           r"$x<3$", r"$4x<12$, so $x<3$.",
           ["x<3", "<3"]),
      item("linear-e3", "easy",
           r"Find the gradient of the line through $(0,1)$ and $(2,5)$.",
           r"$2$", r"$m=(5-1)/(2-0)=2$.",
           ["2", "m=2"]),
      item("linear-e4", "easy",
           r"Solve $x+5=0$.",
           r"$x=-5$", r"Subtract $5$ from both sides.",
           ["-5", "x=-5"]),
      item("linear-e5", "easy",
           r"Find the $y$-intercept of $y=3x-4$.",
           r"$-4$", r"When $x=0$, $y=-4$.",
           ["-4", "c=-4", "(0,-4)"]),
      item("linear-2", "medium",
           r"Solve $2(x-4)=x+1$.",
           r"$x=9$", r"$2x-8=x+1$, so $x=9$.",
           ["9", "x=9"]),
      item("linear-4", "medium",
           r"The line through $(1,2)$ and $(3,8)$ has equation $y=mx+c$. Find $m$.",
           r"$3$", r"$m=(8-2)/(3-1)=3$.",
           ["3", "m=3"]),
      item("linear-5", "medium",
           r"Solve the system $x+y=10$, $x-y=2$. Give $x$ and $y$.",
           r"$x=6$, $y=4$", r"Adding the equations gives $2x=12$. Then $y=4$.",
           ["x=6,y=4", "6,4", "(6,4)"]),
      item("linear-m4", "medium",
           r"Find the equation of the line with gradient $-2$ through $(1,5)$, in the form $y=mx+c$.",
           r"$y=-2x+7$", r"$5=-2(1)+c$ so $c=7$.",
           ["y=-2x+7", "-2x+7"]),
      item("linear-m5", "medium",
           r"Solve $3x-1\ge 2x+4$.",
           r"$x\ge 5$", r"$3x-2x\ge 4+1$, so $x\ge 5$.",
           ["x>=5", "x≥5", ">=5"]),
      item("linear-h1", "hard",
           r"Find where $y=2x+1$ meets $y=-x+7$. Give the point.",
           r"$(2,5)$", r"$2x+1=-x+7$ so $3x=6$, $x=2$, $y=5$.",
           ["(2,5)", "2,5"]),
      item("linear-h2", "hard",
           r"A line is perpendicular to $y=\dfrac{1}{3}x+2$ and passes through $(0,4)$. Find its equation.",
           r"$y=-3x+4$", r"Perpendicular gradient is $-3$. Through $(0,4)$: $y=-3x+4$.",
           ["y=-3x+4", "-3x+4"]),
      item("linear-h3", "hard",
           r"Solve $\dfrac{x-1}{2}+\dfrac{x+1}{3}=4$.",
           r"$x=5$", r"Multiply by $6$: $3(x-1)+2(x+1)=24$, so $5x-1=24$, $x=5$.",
           ["5", "x=5"]),
      item("linear-h4", "hard",
           r"Find the distance between $(1,2)$ and $(4,6)$.",
           r"$5$", r"$\sqrt{(4-1)^{2}+(6-2)^{2}}=\sqrt{9+16}=5$.",
           ["5"]),
      item("linear-h5", "hard",
           r"Solve the system $2x+y=7$, $3x-2y=0$. Give $x$ and $y$.",
           r"$x=2$, $y=3$", r"From the second, $y=\dfrac{3x}{2}$. Then $2x+\dfrac{3x}{2}=7$, so $\dfrac{7x}{2}=7$, $x=2$, $y=3$.",
           ["x=2,y=3", "2,3", "(2,3)"]),
    ],
  },
  {
    "id": "quadratics", "order": 4,
    "title": "Quadratics",
    "blurb": "Factor, discriminant, and completed square.",
    "hlLink": "HL functions live on vertex form, equal roots, and intersections.",
    "items": [
      item("quadratics-1", "easy",
           r"Solve $x^{2}-5x+6=0$.",
           r"$x=2$ or $x=3$", r"$(x-2)(x-3)=0$.",
           ["2,3", "x=2 or x=3", "3,2"]),
      item("quadratics-4", "easy",
           r"Write down the vertex of $y=(x-2)^{2}+5$.",
           r"$(2,5)$", r"Vertex form $y=(x-h)^{2}+k$ has vertex $(h,k)$.",
           ["(2,5)", "2,5"]),
      item("quadratics-e3", "easy",
           r"Solve $x^{2}=9$.",
           r"$x=\pm 3$", r"$x=3$ or $x=-3$.",
           ["+-3", "3,-3", "±3", "x=+-3"]),
      item("quadratics-e4", "easy",
           r"Expand $(x+1)(x-5)$.",
           r"$x^{2}-4x-5$", r"$x^{2}-5x+x-5=x^{2}-4x-5$.",
           ["x^2-4x-5"]),
      item("quadratics-e5", "easy",
           r"State the axis of symmetry of $y=(x+3)^{2}-1$.",
           r"$x=-3$", r"The axis is $x=h$ where $h=-3$.",
           ["x=-3", "-3"]),
      item("quadratics-2", "medium",
           r"Find the discriminant of $2x^{2}+3x+4$.",
           r"$-23$", r"$b^{2}-4ac=9-32=-23$. No real roots.",
           ["-23"]),
      item("quadratics-5", "medium",
           r"Solve $x^{2}=12$, leaving the answer in surd form.",
           r"$x=\pm 2\sqrt{3}$", r"$x=\pm\sqrt{12}=\pm 2\sqrt{3}$.",
           ["+-2sqrt(3)", "2sqrt(3),-2sqrt(3)", "±2sqrt(3)"]),
      item("quadratics-3", "medium",
           r"Write $x^{2}+6x+2$ in the form $(x-h)^{2}+k$.",
           r"$(x+3)^{2}-7$", r"Half of $6$ is $3$, and $3^{2}=9$, so $x^{2}+6x+2=(x+3)^{2}-7$.",
           ["(x+3)^2-7", "(x+3)^2+(-7)"]),
      item("quadratics-m4", "medium",
           r"Solve $x^{2}-4x-5=0$ by factorising.",
           r"$x=5$ or $x=-1$", r"$(x-5)(x+1)=0$.",
           ["5,-1", "-1,5", "x=5 or x=-1"]),
      item("quadratics-m5", "medium",
           r"Find the $y$-intercept of $y=x^{2}-3x+2$.",
           r"$2$", r"Set $x=0$: $y=2$.",
           ["2", "(0,2)"]),
      item("quadratics-h1", "hard",
           r"Solve $2x^{2}-5x-3=0$.",
           r"$x=3$ or $x=-\dfrac{1}{2}$", r"$(2x+1)(x-3)=0$.",
           ["3,-1/2", "-1/2,3", "x=3 or x=-1/2"]),
      item("quadratics-h2", "hard",
           r"Find the values of $k$ for which $x^{2}+kx+9=0$ has equal roots.",
           r"$k=\pm 6$", r"Discriminant $k^{2}-36=0$, so $k=\pm 6$.",
           ["+-6", "6,-6", "±6", "k=+-6"]),
      item("quadratics-h3", "hard",
           r"Complete the square: $2x^{2}+8x+3$. Write in the form $a(x+h)^{2}+k$.",
           r"$2(x+2)^{2}-5$", r"$2(x^{2}+4x)+3=2((x+2)^{2}-4)+3=2(x+2)^{2}-5$.",
           ["2(x+2)^2-5"]),
      item("quadratics-h4", "hard",
           r"The quadratic $x^{2}-6x+c=0$ has roots that sum to $6$ and multiply to $c$. If one root is $2$, find $c$.",
           r"$8$", r"Other root is $4$ (sum $6$), product $c=8$.",
           ["8", "c=8"]),
      item("quadratics-h5", "hard",
           r"Find the minimum value of $y=x^{2}-4x+7$.",
           r"$3$", r"$(x-2)^{2}+3$, so minimum is $3$.",
           ["3", "y=3"]),
    ],
  },
  {
    "id": "logs", "order": 5,
    "title": "Exponents & logs",
    "blurb": "The log laws before the HL questions get clever.",
    "hlLink": "Inverse of an exponential, and half of the algebra paper, sits on this.",
    "items": [
      item("logs-1", "easy",
           r"Evaluate $\log_{2} 32$.",
           r"$5$", r"$2^{5}=32$.", ["5"]),
      item("logs-2", "easy",
           r"Evaluate $\log_{10} 1000$.",
           r"$3$", r"$10^{3}=1000$.", ["3"]),
      item("logs-3", "easy",
           r"Evaluate $\log_{3} 27$.",
           r"$3$", r"$3^{3}=27$.", ["3"]),
      item("logs-5", "easy",
           r"Evaluate $\ln(e^{3})$.",
           r"$3$", r"$\ln$ and $e^{(\cdot)}$ are inverses, so the result is $3$.", ["3"]),
      item("logs-e5", "easy",
           r"Evaluate $\log_{5} 1$.",
           r"$0$", r"$5^{0}=1$.", ["0"]),
      item("logs-4", "medium",
           r"Solve $3^{x}=81$.",
           r"$x=4$", r"$81=3^{4}$.", ["4", "x=4"]),
      item("logs-m2", "medium",
           r"Simplify $\log_{2} 8+\log_{2} 4$.",
           r"$5$", r"$\log_{2}(8\cdot 4)=\log_{2} 32=5$, or $3+2=5$.", ["5"]),
      item("logs-m3", "medium",
           r"Solve $2^{x}=1/8$.",
           r"$x=-3$", r"$1/8=2^{-3}$.", ["-3", "x=-3"]),
      item("logs-m4", "medium",
           r"Evaluate $\log_{4} 64$.",
           r"$3$", r"$4^{3}=64$.", ["3"]),
      item("logs-m5", "medium",
           r"Simplify $\ln e^{5}-\ln e^{2}$.",
           r"$3$", r"$5-2=3$.", ["3"]),
      item("logs-h1", "hard",
           r"Solve $\log_{2}(x-1)=3$.",
           r"$x=9$", r"$x-1=2^{3}=8$, so $x=9$.", ["9", "x=9"]),
      item("logs-h2", "hard",
           r"Solve $5^{2x}=25$.",
           r"$x=1$", r"$25=5^{2}$, so $2x=2$ and $x=1$.", ["1", "x=1"]),
      item("logs-h3", "hard",
           r"Simplify $\dfrac{\log 100}{\log 10}$ (same base).",
           r"$2$", r"Change of base, or $\log 100=2\log 10$.", ["2"]),
      item("logs-h4", "hard",
           r"Solve $\log_{3} x+\log_{3}(x-2)=1$.",
           r"$x=3$", r"$\log_{3}(x(x-2))=1$ so $x^{2}-2x=3$, $x^{2}-2x-3=0$, $(x-3)(x+1)=0$. Domain needs $x>2$, so $x=3$.",
           ["3", "x=3"]),
      item("logs-h5", "hard",
           r"Express $\log_{2} 12$ in terms of $\log_{2} 3$.",
           r"$2+\log_{2} 3$", r"$12=4\cdot 3$, so $\log_{2} 12=2+\log_{2} 3$.",
           ["2+log_2(3)", "2+log2(3)", "log2(3)+2"]),
    ],
  },
  {
    "id": "functions", "order": 6,
    "title": "Function notation",
    "blurb": "Evaluate, compose, invert a linear, and name a domain.",
    "hlLink": "Paper 1 opens on $f\\circ g$ and $f^{-1}$ more often than people expect.",
    "items": [
      item("functions-1", "easy",
           r"Let $f(x)=3x-1$. Find $f(4)$.",
           r"$11$", r"$3\cdot 4-1=11$.", ["11"]),
      item("functions-5", "easy",
           r"For which value of $x$ is $f(x)=\dfrac{1}{x-2}$ undefined?",
           r"$x=2$", r"The denominator is zero when $x=2$.", ["2", "x=2"]),
      item("functions-e3", "easy",
           r"Let $f(x)=x^{2}$. Find $f(-3)$.",
           r"$9$", r"$(-3)^{2}=9$.", ["9"]),
      item("functions-e4", "easy",
           r"Let $g(x)=5-x$. Find $g(2)$.",
           r"$3$", r"$5-2=3$.", ["3"]),
      item("functions-e5", "easy",
           r"State the range of $f(x)=x^{2}$ for real $x$.",
           r"$y\ge 0$", r"Squares are never negative.",
           ["y>=0", "y≥0", "[0,inf)", "[0,infinity)"]),
      item("functions-2", "medium",
           r"Let $f(x)=x+1$ and $g(x)=x^{2}$. Find $(g\circ f)(2)$.",
           r"$9$", r"$f(2)=3$ and $g(3)=9$.", ["9"]),
      item("functions-4", "medium",
           r"State the domain of $f(x)=\sqrt{x-4}$.",
           r"$x\ge 4$", r"The expression under the square root cannot be negative.",
           ["x>=4", "x≥4", "[4,inf)", "[4,infinity)"]),
      item("functions-3", "medium",
           r"Find the inverse of $f(x)=2x+6$.",
           r"$f^{-1}(x)=\dfrac{x-6}{2}$", r"Set $y=2x+6$, swap, and solve: $x=(y-6)/2$.",
           ["(x-6)/2", "x/2-3"]),
      item("functions-m4", "medium",
           r"Let $f(x)=2x$ and $g(x)=x-3$. Find $(f\circ g)(5)$.",
           r"$4$", r"$g(5)=2$, $f(2)=4$.", ["4"]),
      item("functions-m5", "medium",
           r"If $f(x)=x^{2}-1$, find $f(f(2))$.",
           r"$8$", r"$f(2)=3$, $f(3)=8$.", ["8"]),
      item("functions-h1", "hard",
           r"Find $(f\circ g)(x)$ if $f(x)=x^{2}$ and $g(x)=x+1$.",
           r"$(x+1)^{2}$", r"$f(g(x))=(x+1)^{2}$.",
           ["(x+1)^2", "x^2+2x+1"]),
      item("functions-h2", "hard",
           r"Find $f^{-1}(x)$ if $f(x)=\dfrac{x+1}{3}$.",
           r"$f^{-1}(x)=3x-1$", r"$y=(x+1)/3$ so $x=3y-1$.",
           ["3x-1", "f^{-1}(x)=3x-1"]),
      item("functions-h3", "hard",
           r"State the domain of $f(x)=\dfrac{1}{\sqrt{x-1}}$.",
           r"$x>1$", r"Need $x-1>0$ (strict, since denominator).",
           ["x>1", "(1,inf)", "(1,infinity)"]),
      item("functions-h4", "hard",
           r"Let $f(x)=3x-2$. Find $a$ such that $f(a)=10$.",
           r"$a=4$", r"$3a-2=10$, $3a=12$, $a=4$.", ["4", "a=4"]),
      item("functions-h5", "hard",
           r"If $f(x)=2x+1$ and $g(x)=x^{2}$, find $(g\circ f)^{-1}(9)$ wait — simpler: find $(f\circ g)(2)$.",
           r"$9$", r"$g(2)=4$, $f(4)=9$.", ["9"]),
    ],
  },
  {
    "id": "trig", "order": 7,
    "title": "Right-triangle trig",
    "blurb": "Pythagoras, exact values, and radians.",
    "hlLink": "HL identities are unpleasant if $sin 60^{\\circ}$ is not instant.",
    "items": [
      item("trig-2", "easy",
           r"Write down the exact value of $\cos 60^{\circ}$.",
           r"$\dfrac{1}{2}$", r"This is a standard exact value.", ["1/2", "0.5"]),
      item("trig-4", "easy",
           r"Convert $180^{\circ}$ to radians.",
           r"$\pi$", r"Half a turn is $\pi$ radians.", ["pi", "π"]),
      item("trig-e3", "easy",
           r"Write down the exact value of $\sin 90^{\circ}$.",
           r"$1$", r"Standard exact value.", ["1"]),
      item("trig-e4", "easy",
           r"Convert $90^{\circ}$ to radians.",
           r"$\dfrac{\pi}{2}$", r"A right angle is $\pi/2$.", ["pi/2", "π/2"]),
      item("trig-e5", "easy",
           r"Write down the exact value of $\tan 45^{\circ}$.",
           r"$1$", r"Opposite equals adjacent in an isosceles right triangle.", ["1"]),
      item("trig-1", "medium",
           r"A right triangle has opposite side $3$ and adjacent side $4$. Find $\sin\theta$ for that acute angle.",
           r"$\dfrac{3}{5}$", r"The hypotenuse is $5$, so $\sin\theta=3/5$.", ["3/5", "0.6"]),
      item("trig-3", "medium",
           r"Write down the exact value of $\sin 45^{\circ}$.",
           r"$\dfrac{\sqrt{2}}{2}$", r"In an isosceles right triangle the opposite and hypotenuse are in the ratio $1:\sqrt{2}$.",
           ["sqrt(2)/2", "1/sqrt(2)"]),
      item("trig-5", "medium",
           r"Write down the exact value of $\tan 30^{\circ}$.",
           r"$\dfrac{1}{\sqrt{3}}$", r"$\tan 30^{\circ}=1/\sqrt{3}=\sqrt{3}/3$.",
           ["1/sqrt(3)", "sqrt(3)/3"]),
      item("trig-m4", "medium",
           r"Convert $\dfrac{\pi}{3}$ radians to degrees.",
           r"$60^{\circ}$", r"$\pi$ rad $=180^{\circ}$, so $\pi/3=60^{\circ}$.",
           ["60", "60deg", "60°"]),
      item("trig-m5", "medium",
           r"Write down the exact value of $\cos 30^{\circ}$.",
           r"$\dfrac{\sqrt{3}}{2}$", r"Standard exact value.",
           ["sqrt(3)/2"]),
      item("trig-h1", "hard",
           r"A right triangle has legs $5$ and $12$. Find $\cos\theta$ where $\theta$ is opposite the side $5$.",
           r"$\dfrac{12}{13}$", r"Hypotenuse $13$; adjacent to that angle is $12$.",
           ["12/13"]),
      item("trig-h2", "hard",
           r"Find the exact value of $\sin 150^{\circ}$.",
           r"$\dfrac{1}{2}$", r"$\sin(180^{\circ}-30^{\circ})=\sin 30^{\circ}=1/2$.",
           ["1/2", "0.5"]),
      item("trig-h3", "hard",
           r"Convert $225^{\circ}$ to radians, in terms of $\pi$.",
           r"$\dfrac{5\pi}{4}$", r"$225/180\cdot\pi=5\pi/4$.",
           ["5pi/4", "5π/4"]),
      item("trig-h4", "hard",
           r"If $\cos\theta=\dfrac{3}{5}$ and $\theta$ is acute, find $\tan\theta$.",
           r"$\dfrac{4}{5}$", r"Opposite is $4$ (Pythagoras), so $\tan\theta=4/5$. Wait — opp/adj $=4/3$.",
           ["4/3"]),
      item("trig-h5", "hard",
           r"Find the exact value of $\sin^{2} 30^{\circ}+\cos^{2} 30^{\circ}$.",
           r"$1$", r"Pythagorean identity: $\sin^{2}\theta+\cos^{2}\theta=1$.",
           ["1"]),
    ],
  },
  {
    "id": "chance", "order": 8,
    "title": "Data & chance",
    "blurb": "Mean, median, and the first probability rules.",
    "hlLink": "Combined events and binomial probability assume these without a reminder.",
    "items": [
      item("chance-1", "easy",
           r"Find the mean of $2, 5, 8, 5$.",
           r"$5$", r"$(2+5+8+5)/4=20/4=5$.", ["5"]),
      item("chance-5", "easy",
           r"Find the median of $1, 4, 7, 9, 12$.",
           r"$7$", r"The ordered list has five values, so the middle one is $7$.", ["7"]),
      item("chance-2", "easy",
           r"A fair six-sided die is rolled. Find the probability of an even number.",
           r"$\dfrac{1}{2}$", r"Three of the six faces are even.", ["1/2", "0.5", "3/6"]),
      item("chance-3", "easy",
           r"If $\mathrm{P}(A)=0.3$, find $\mathrm{P}(A')$.",
           r"$0.7$", r"The complement is $1-0.3$.", ["0.7", "7/10"]),
      item("chance-e5", "easy",
           r"Find the mode of $3, 5, 3, 7, 3, 8$.",
           r"$3$", r"$3$ appears most often.", ["3"]),
      item("chance-4", "medium",
           r"Two fair coins are flipped. Find the probability of two heads.",
           r"$\dfrac{1}{4}$", r"The outcomes are HH, HT, TH, TT, all equally likely.", ["1/4", "0.25"]),
      item("chance-m2", "medium",
           r"Find the range of $4, 9, 2, 11, 6$.",
           r"$9$", r"$11-2=9$.", ["9"]),
      item("chance-m3", "medium",
           r"A bag has $3$ red and $5$ blue balls. One is drawn at random. Find $\mathrm{P}(\text{red})$.",
           r"$\dfrac{3}{8}$", r"$3$ out of $8$.", ["3/8", "0.375"]),
      item("chance-m4", "medium",
           r"Find the mean of $10, 20, 30, 40$.",
           r"$25$", r"$100/4=25$.", ["25"]),
      item("chance-m5", "medium",
           r"If $\mathrm{P}(A)=0.4$ and $\mathrm{P}(B)=0.5$ and $A,B$ are mutually exclusive, find $\mathrm{P}(A\cup B)$.",
           r"$0.9$", r"Add: $0.4+0.5=0.9$.", ["0.9", "9/10"]),
      item("chance-h1", "hard",
           r"Two fair dice are rolled. Find the probability both show a $6$.",
           r"$\dfrac{1}{36}$", r"$1/6\times 1/6=1/36$.", ["1/36"]),
      item("chance-h2", "hard",
           r"Find the median of $2, 5, 7, 10, 12, 15$.",
           r"$8.5$", r"Middle two are $7$ and $10$; mean is $8.5$.", ["8.5", "17/2"]),
      item("chance-h3", "hard",
           r"A fair die is rolled. Find $\mathrm{P}(\text{prime number})$.",
           r"$\dfrac{1}{2}$", r"Primes on a die: $2,3,5$ — three of six.", ["1/2", "0.5", "3/6"]),
      item("chance-h4", "hard",
           r"If $\mathrm{P}(A)=0.6$, $\mathrm{P}(B)=0.5$, $\mathrm{P}(A\cap B)=0.3$, find $\mathrm{P}(A\cup B)$.",
           r"$0.8$", r"$0.6+0.5-0.3=0.8$.", ["0.8", "4/5"]),
      item("chance-h5", "hard",
           r"From $\{1,2,3,4,5\}$, two distinct numbers are chosen at random. Find $\mathrm{P}(\text{both odd})$.",
           r"$\dfrac{3}{10}$", r"Odds: $1,3,5$. Ways: $\binom{3}{2}/\binom{5}{2}=3/10$.",
           ["3/10", "0.3"]),
    ],
  },
]

# Fix the trig-h4 answer - I left a contradictory solution. tan = 4/3
for sk in SKILLS:
  if sk["id"] == "trig":
    for it in sk["items"]:
      if it["id"] == "trig-h4":
        it["answer"] = r"$\dfrac{4}{3}$"
        it["solution"] = r"Opposite is $4$ by Pythagoras ($3$-$4$-$5$), so $\tan\theta=4/3$."
        it["accept"] = ["4/3"]

# Fix functions-h5 - the prompt is awkward; clean it
for sk in SKILLS:
  if sk["id"] == "functions":
    for it in sk["items"]:
      if it["id"] == "functions-h5":
        it["prompt"] = r"If $f(x)=2x+1$ and $g(x)=x^{2}$, find $(f\circ g)(2)$."
        it["answer"] = r"$9$"
        it["solution"] = r"$g(2)=4$, $f(4)=9$."
        it["accept"] = ["9"]

def main():
  # validate counts
  for sk in SKILLS:
    from collections import Counter
    c = Counter(i["stage"] for i in sk["items"])
    assert len(sk["items"]) == 15, (sk["id"], len(sk["items"]))
    assert c["easy"] == 5 and c["medium"] == 5 and c["hard"] == 5, (sk["id"], dict(c))
    ids = [i["id"] for i in sk["items"]]
    assert len(ids) == len(set(ids)), sk["id"]

  out = ROOT / "data" / "skills.json"
  out.write_text(json.dumps(SKILLS, indent=2, ensure_ascii=False) + "\n")
  (ROOT / "site" / "data" / "skills.json").write_text(out.read_text())
  print(f"Wrote {len(SKILLS)} skills, {sum(len(s['items']) for s in SKILLS)} items → {out}")

if __name__ == "__main__":
  main()
